baseurl = "https://www.joshuaulrich.com/"
title = "Joshua Ulrich"
languageCode = "en-us"
publishDir = "docs"

theme = [ "beautifulhugo" ]
googleAnalytics = "G-02NEF26L3P"

[Params]
  homeTitle = "About me"
  socialShare = true
  since = 2010

[Author]
  email = "josh.m.ulrich@gmail.com"
  github = "joshuaulrich"
  twitter = "joshua_ulrich"
  linkedin = "joshuaulrich"
  stackoverflow = "users/271616/joshua-ulrich"

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url  = "/portfolio/"
    weight = 2

[[menu.main]]
    identifier = "resume"
    name = "Resume"
    url  = "/resume/"
    weight = 3

